name: schema-change-demo
 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**' # Adjust the path as needed
 
jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
 
      - name: Install schemachange
        run: pip install schemachange
 
      - name: Run schemachange
        env:
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          schemachange -f $GITHUB_WORKSPACE/migrations \
            -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE \
            -w $SF_WAREHOUSE -d $SF_DATABASE \
            -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
