on:
  push:
    paths:
      - 'dbscripts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install schemachange  

      - name: Run schemachange
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          schemachange -f dbscripts \
          --snowflake-account $SNOWFLAKE_ACCOUNT \
          --snowflake-user $SNOWFLAKE_USER \
          --snowflake-role $SNOWFLAKE_ROLE \
          --snowflake-warehouse $SNOWFLAKE_WAREHOUSE \
          --snowflake-database $SNOWFLAKE_DATABASE \
          --snowflake-schema $SNOWFLAKE_SCHEMA \
          --snowflake-password $SNOWFLAKE_PASSWORD