---
on:
  push:
    branches:
      - main
    paths:
      - migrations/**
  workflow_dispatch: null
jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        run: >
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

          python --version

          echo "Step 1: Installing schemachange"

          pip install schemachange

          echo ${{ secrets.SF_DATABASE }} | sed 's/./& /g'


          echo "Step 2: Running schemachange"

          run: |

          for script in dbscripts/*.sql; do
           snowsql -a "$SNOWFLAKE_ACCOUNT" -u "$SNOWFLAKE_USER" -r "$SNOWFLAKE_WAREHOUSE" -d "$SNOWFLAKE_DATABASE" -s "$SNOWFLAKE_SCHEMA" -p "$SNOWFLAKE_PASSWORD" -f "$script"
          done
